[tool.poetry]
name = "observer"
version = "1.0.4"
description = "Graphical console and central information provider for NECST system"
license = "MIT"
readme = "README.md"
authors = ["KaoruNishikawa <k.nishikawa@a.phys.nagoya-u.ac.jp>"]
homepage = "https://github.com/necst-telescope/observer"
repository = "https://github.com/necst-telescope/observer"

[tool.poetry.scripts]
observer = "observer.server:main"

[tool.poetry.dependencies]
python = "^3.12"
Flask = ">=2.2,<3.0"
Flask-SocketIO = "^5.3.6"
psutil = "^5.9.8"
simple-websocket = "^1.0.0"
tomlkit = "^0.11.4"

[tool.poetry.group.dev.dependencies]
black = "^24.3"
flake8 = "^7.0"
ipykernel = "^6.29"
myst-parser = "^2.0"
notebook = "^7.2"
pydata-sphinx-theme = "^0.15"
pytest = "^9.0"
sphinx = "^7.2"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
